language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES=''
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='serde'
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='yolocrypto nightly'
  - TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES='' 

matrix:
  exclude:
    # Test nightly features, such as radix_51, only on nightly.
    - rust: stable
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
    - rust: beta
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='nightly'
    - rust: stable
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='yolocrypto nightly'
    - rust: beta
      env: TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='yolocrypto nightly'
    # Test no_std only on nightly.
    - rust: stable
      env: TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES=''
    - rust: beta
      env: TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES=''
    - rust: nightly
      env: TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES='alloc'

script:
  - cargo $TEST_COMMAND --features="$FEATURES" $EXTRA_FLAGS

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
