language: rust

rust:
  - stable
  - nightly

env:
  # Tests the u32 backend
  - TEST_COMMAND=test EXTRA_FLAGS='--no-default-features' FEATURES='std u32_backend'
  # Tests the u64 backend
  - TEST_COMMAND=test EXTRA_FLAGS='--no-default-features' FEATURES='std u64_backend'
  # Tests the avx2 backend
  - TEST_COMMAND=test EXTRA_FLAGS='--no-default-features' FEATURES='std avx2_backend yolocrypto'
  # Tests serde support and default feature selection
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='serde'
  # Tests building without std
  - TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES='' 

matrix:
  exclude:
    # Test the avx2 backend only on nightly
    - rust: stable
      env: TEST_COMMAND=test EXTRA_FLAGS='--no-default-features' FEATURES='std avx2_backend yolocrypto'
    # Test no_std only on nightly.
    - rust: stable
      env: TEST_COMMAND=build EXTRA_FLAGS=--no-default-features FEATURES='' 

script:
  - cargo $TEST_COMMAND --features="$FEATURES" $EXTRA_FLAGS

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
