[package]
name = "curve25519-dalek"
version = "0.13.0"
authors = ["Isis Lovecruft <isis@patternsinthevoid.net>",
           "Henry de Valence <hdevalence@hdevalence.ca>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/isislovecruft/curve25519-dalek"
homepage = "https://code.ciph.re/isis/curve25519-dalek"
documentation = "https://docs.rs/curve25519-dalek"
categories = ["cryptography", "no-std"]
keywords = ["cryptography", "curve25519", "elliptic", "curve", "ECC"]
description = "A low-level cryptographic library for point, group, field, and scalar operations on a curve isomorphic to the twisted Edwards curve defined by -x²+y² = 1 - 121665/121666 x²y² over GF(2²⁵⁵ - 19)."
exclude = [
    ".gitignore"
]

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header rustdoc-include-katex-header.html"]

[badges]
travis-ci = { repository = "isislovecruft/curve25519-dalek", branch = "master"}

[dependencies.serde]
version = "1.0"
optional = true

[dependencies.arrayref]
version = "0.3.4"

[dependencies.rand]
optional = true
version = "0.3"

[dependencies.digest]
version = "0.6"

[dependencies.subtle]
version = "^0.3"
default-features = false

[dependencies.generic-array]
# same version that digest depends on
version = "^0.8"

[dev-dependencies.sha2]
version = "0.6"

[dev-dependencies.serde_cbor]
version = "0.6"

[features]
nightly = ["radix_51", "subtle/nightly"]
default = ["std"]
std = ["rand", "subtle/std"]
alloc = []
# This isn't used at the moment, but keep it around for future yolocrypto features.
yolocrypto = []
bench = []
# Radix-51 arithmetic using u128
radix_51 = []
